export function DINotFoundException(message) {
   return new ErrorEvent(message)
}
